version: "1.0.0"
services:
  docker-hoster:
    image: dvdarias/docker-hoster
    container_name: docker-hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
  postgres:
    image: postgres:15.3
    container_name: postgres
    environment:
      POSTGRES_USER: pimsec
      POSTGRES_PASSWORD: pimsec
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    depends_on:
      - docker-hoster
  pgadmin:
    image: dpage/pgadmin4:7.4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: oleg.zhuravlev@pirobase-imperia.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8081:80
    depends_on:
      postgres:
        condition: service_healthy
