spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:postgresql://postgres:5432/pimsecurity
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      data-locations:
        - classpath:db_init/acl_schema.sql
        - classpath:db_init/acl_permissions.sql
        - classpath:db_init/users.sql
#        - classpath:db_init/items.sql
#        - classpath:db_init/sequences.sql
  jpa:
    properties: # Passed on to the JPA implementation.
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create-drop
    defer-datasource-initialization: true
logging:
  level:
    ROOT: DEBUG
#    org:
#      hibernate:
#        type: trace
server:
  port: 8080

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: swag
