-- Entities
ALTER SEQUENCE items_id_seq RESTART WITH 1000;
ALTER SEQUENCE users_id_seq RESTART WITH 1000;
ALTER SEQUENCE authorities_id_seq RESTART WITH 1000;
-- ACL
ALTER SEQUENCE acl_class_id_seq RESTART WITH 1000;
ALTER SEQUENCE acl_entry_id_seq RESTART WITH 1000;
ALTER SEQUENCE acl_object_identity_id_seq RESTART WITH 1000;
ALTER SEQUENCE acl_sid_id_seq RESTART WITH 1000;
